import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Event from '@/components/Events/Events'
import Page from '@/components/teampage/teampage'
import Link from 'next/link'
import { About } from '@/components/About/About'
import HackCBS from '@/components/hackcbs/hackcbs'
import { Footer } from '@/components/footer/footer'
import { Landingpage } from '@/components/landingpage/landingpage'
// import { About } from '@/components/About/About'
// import { Footer } from '@/components/footer/footer'
const inter = Inter({ subsets: ['latin'] })
// import { Landingpage } from '@/components/landingpage/landingpage'
// import HackCBS from '@/components/hackcbs/hackcbs'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossOrigin="anonymous"></link>
        <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossOrigin="anonymous"></script>
        {/* <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"></link> */}
        {/* <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script> */}
        <link rel="shortcut icon" type="image/png" href="assets/images/Kronos_White.png"/>
    <link rel="stylesheet" href="vendor/css/aos.css" />
    <meta name='viewport' content='width=device-width, initial-scale=1'/>
    <link rel="preconnect" href="https://fonts.gstatic.com"/>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet"/>
    <link rel='stylesheet' type='text/css' media='screen' href='vendor/css/bootstrap.min.css'/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous"/>
    <link rel='stylesheet' type='text/css' media='screen' href='src/css/kronos.css' class="theme-link"/>
    <script src='vendor/js/bootstrap.min.js'></script>
    <script src='vendor/js/jquery-2.2.4.min.js'></script>
    <script src='src/js/header.js'></script>
   
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="shortcut icon" type="image/png" href="assets/images/Kronos_White.png"/>
  
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous"/>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="src/css/teampg.css" class="teamPg-theme-link"/>
    <link rel='stylesheet' type='text/css' media='screen' href='vendor/css/bootstrap.min.css'/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous"/>
    <link rel='stylesheet' type='text/css' media='screen' href='src/css/kronos.css' class="theme-link"/>
    <script src='vendor/js/jquery-2.2.4.min.js'></script>

    <script src='src/js/header.js'></script>
   
    <link rel="preconnect" href="https://fonts.gstatic.com"/>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet"/>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>

      </Head>
         
       <Landingpage/>
      <About/>
      <HackCBS/>
      <Event/>
      <Footer/>
      

      {/* <Page/> */}
      
      <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r121/three.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.waves.min.js"></script>
    <script src="src/js/kronos.js"></script>

    <script src="https://cdn.lordicon.com/libs/frhvbuzj/lord-icon-2.0.2.js"></script>

    <script src="vendor/js/aos.js"></script>

    </>
  )
}